-keep class org.bouncycastle.** { *; }
-keep class org.conscrypt.** { *; }
-keep class okhttp3.** { *; }
-keep class okio.** { *; }
-keep class com.mohan.pensieve.vpn.** { *; }
-dontwarn org.bouncycastle.**
-dontwarn org.conscrypt.**
-dontwarn okhttp3.**
-dontwarn okio.**
